[mypy]
python_version = 3.12
strict = True
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
no_implicit_optional = True
show_error_codes = True

[mypy-pyroomacoustics.*]
ignore_missing_imports = True

[mypy-soundfile.*]
ignore_missing_imports = True

[mypy-piper.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-onnxruntime.*]
ignore_missing_imports = True

[mypy-ctranslate2.*]
ignore_missing_imports = True

[mypy-faster_whisper.*]
ignore_missing_imports = True

[mypy-speechbrain.*]
ignore_missing_imports = True

[mypy-jiwer.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True
